[package]
name = "script"
version = "0.1.0"
edition = "2021"

[dependencies]
sp1-sdk = "4.0.0"
rusqlite = { version = "0.28.0", features = ["functions"] }
num-bigint = { version = "0.4", features = ["rand"] }
num-traits = "0.2"